version: "3"

services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - phpfpm

  phpfpm:
    image: devilbox/php-fpm:7.2-prod
    volumes:
      - ./src:/var/www/html
    entrypoint: '/bin/sh -c "cd /var/www/html && php artisan migrate && php artisan view:clear && php artisan cache:clear && php artisan db:seed && /docker-entrypoint.sh"'
    links:
      - mysql
      - mongodb
    depends_on:
      - mysql:
        condition: 'service_healthy'

  mongodb:
    image: mongo
    expose:
      - 27017
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "lite"

  mysql:
    image: mysql
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
    healthcheck:
      test: "exit 0"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "lite"

  composer:
    image: composer
    command: install
    volumes:
      - ./src:/app
    command: ["composer", "update", "--ignore-platform-reqs"]
