version: "3"

services:
  web:
    image: library/nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpfpm
    links:
      - phpfpm

  phpfpm:
    image: devilbox/php-fpm:7.2-prod
    volumes:
      - ./src:/var/www/html
    entrypoint: '/bin/sh -c "cd /var/www/html && php artisan key:generate && php artisan migrate --force && php artisan view:clear && php artisan cache:clear && php artisan db:seed --force && /docker-entrypoint.sh"'
    depends_on:
      - mysql
      - mongodb
      - composer
    links:
      - mysql
      - mongodb

  mongodb:
    image: library/mongo
    expose:
      - 27017
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "lite"

  mysql:
    image: library/mysql:5
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "lite"

  composer:
    image: library/composer
    command: install
    volumes:
      - ./src:/app
    command: ["composer", "install", "--ignore-platform-reqs"]
