version: "3"

services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - phpfpm

  phpfpm:
    image: devilbox/php-fpm:7.2-prod
    volumes:
      - ./src:/var/www/html
    entrypoint: '/bin/sh -c "cd /var/www/html && php artisan migrate && php artisan view:clear && php artisan cache:clear && /docker-entrypoint.sh"'
    links:
      - mysql
      - mongodb

  mongodb:
    image: mongo
    # environment:
    #   - MONGO_DATA_DIR=/data/db
    #   - MONGO_LOG_DIR=/dev/null
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "lite"

  mysql:
    image: mysql
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "lite"

  composer:
    image: composer
    command: install
    volumes:
      - ./src:/app
    command: ["composer", "update", "--ignore-platform-reqs"]
